<a href="https://colab.research.google.com/github/s4bih/a/blob/main/numpy_and_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

In [11]:
arr=np.array([1,32,4,135,223])
print(arr)
print(type(arr))
print("data shape",arr.shape)
print("data dimension",arr.ndim)
print("data size",arr.size)



[  1  32   4 135 223]
<class 'numpy.ndarray'>
data shape (5,)
data dimension 1
data size 5
data type int64


In [12]:
c = np.array([[1,2,3], [4,5,6]])
print(c)
print(type(c))
print("data shape",c.shape)
print("data dimension",c.ndim)
print("data size",c.size)


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
data shape (2, 3)
data dimension 2
data size 6


In [ ]:
characterarr=np.array(["a","b","c","d"])
print(characterarr)
print(type(characterarr))
print("data shape",characterarr.shape)
print("data dimension",characterarr.ndim)
print("data size",characterarr.size)

In [19]:
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array
print(x1)

print(x2)

print(x3)

[4 5 7 1 0 1]
[[3 1 9 8]
 [5 1 2 2]
 [4 2 7 0]]
[[[3 1 2 1 5]
  [5 9 1 6 3]
  [2 0 6 9 0]
  [1 5 6 5 2]]

 [[1 6 6 2 9]
  [1 7 6 8 9]
  [0 6 0 3 0]
  [3 6 7 5 4]]

 [[0 9 9 6 6]
  [4 7 6 8 8]
  [8 1 2 0 6]
  [4 3 2 5 7]]]


In [20]:
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)

[[[[[1 2 3 4 5]]]]]
5
(1, 1, 1, 1, 5)
5


In [21]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr[-1])

12


In [ ]:
print(arr[1:5])

In [22]:
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[2:5:3])

[ 5  6  7  8  9 10 11 12]
[1 2 3 4]
[10 11]
[3]


In [25]:
# prompt: buatkan saya array 2d isinya angka

import numpy as np

# Create a 2D array with random integers
rows = 5  # Number of rows
cols = 4   # Number of columns
min_val = 1 # Minimum value
max_val = 100 # Maximum value

# Create a 2D array of the given size with random integers within the specified range
two_d_array = np.random.randint(min_val, max_val + 1, size=(rows, cols))

two_d_array

array([[12, 74, 17, 43],
       [52, 93, 89, 51],
       [69, 28, 35, 45],
       [80, 73, 42, 58],
       [42, 45, 55, 25]])